# Generated by Django 4.0.5 on 2022-06-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=165)),
                ('slug', models.SlugField(unique=True)),
                ('duration', models.IntegerField()),
                ('duration_unit', models.CharField(max_length=65)),
                ('total_hours', models.IntegerField()),
                ('professor', models.CharField(max_length=65)),
                ('cover', models.ImageField(upload_to='institute/img/')),
            ],
        ),
    ]
