# Generated by Django 4.0.5 on 2022-06-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_remove_course_duration_remove_course_duration_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
