# Generated by Django 4.0.5 on 2022-06-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_course_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='professor',
            new_name='teacher',
        ),
    ]
