# Generated by Django 4.0.5 on 2022-06-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_rename_professor_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(upload_to='staticfiles/institute/images/courses_img'),
        ),
    ]
