# Generated by Django 4.0.5 on 2022-06-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_alter_course_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='more_info',
            field=models.TextField(default='', max_length=165),
        ),
    ]
