# Generated by Django 4.0.5 on 2022-06-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_course_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='more_info',
            field=models.TextField(default=''),
        ),
    ]
